cd nova, cd nixfiles, cd rover
MonashNovaRover/nova pull request #133
Opened 2024-12-13 09:35 UTC by vic-bart

## Description

We're cding places.
- Removed old alias
- Added support for `cd nova/nixfiles/rover/science/gui`, while still keeping their alias equivalents

## Changelogs

## Screenshots

## ROS

## Steps to Test

- `sudo nixos-rebuild switch`
- Try them out!

## Memes

![image](https://github.com/user-attachments/assets/b3274a56-f807-4942-a6d5-472812d41f48)

2024-12-13 10:07 UTC, hacker1024 commented
I don't agree with this interface.

It is very counterintuitive to add fake targets to `cd` like this, especially if one ever needs to change into a real local directory with one of these names, and especially if they don't know the alias exists in the first place.

With a pure alias, it is obvious that a custom command with a non-trivial implementation is being run.

If you really want to add directory aliases that can be used in commands, I recommend [Zsh's functionality](https://til.hashrocket.com/posts/xsavbhlrz4-shortcuts-with-hash-d-in-zsh).

2024-12-13 10:09 UTC, hacker1024 requested changes

2024-12-13 10:09 UTC, hacker1024 commented on nixfiles/modules/home/macros/default.nix
> +      }
You cannot assume that the user keeps Nova source files in the root of their home directory. 

There are NixOS options that should be used instead with string interpolation. See the other aliases for examples.

2024-12-14 01:51 UTC, vic-bart commented on nixfiles/modules/home/macros/default.nix
> +      }
I've swapped them out to use the string interpolation.

2024-12-14 02:03 UTC, vic-bart commented
Am I correct in saying that implementing [Zsh's functionality](https://til.hashrocket.com/posts/xsavbhlrz4-shortcuts-with-hash-d-in-zsh) would mean commands look like `cd ~nova`? In which case, we might as well leave it as `nova`. The purpose of this PR was to specifically allow for `cd nova` (and other aliases) to have the same functionality as `nova` (and their equivalents) &mdash; see [Slack thread](https://monashnovarover.slack.com/archives/C07H7FA2A3Z/p1733540167669469) for context &mdash; so changing it would introduce further confusion.

I've amended the bash shell function to only overwrite the `cd` command if the filepath doesn't exist. For example, if your directory is /home and you want to go to /home/nova, `cd nova` will work as intended. If `nova` isn't a valid filepath, then it will default to `cd ~/nova/src/..`.

Are there any problems with this; in what scenario would this cause issues?

[edit] wait something broke 
[edit] [fixed it](https://stackoverflow.com/questions/12133209/bin-bash-cd-results-in-bin-bash-cd-no-such-file-or-directory-why), "" suck

2025-01-10 23:35 UTC, vic-bart commented
I've since realised that one can overwrite their `cd` within their own NixOS; there's no need to enforce this on everyone, I'll just pin a tutorial somewhere that shows how to implement it in their own NixOS if people want.

2025-01-10 23:36 UTC, closed without merging

2025-05-07 04:16 UTC, RohitPilakkat commented
> I've since realised that one can overwrite their `cd` within their own NixOS; there's no need to enforce this on everyone, I'll just pin a tutorial somewhere that shows how to implement it in their own NixOS if people want.

There's a snippet on Notion that I made ages ago that covers how to add and edit aliases on your own system fyi

https://www.notion.so/NixOS-Overview-Customisation-961daf112a4e4d51b5ff681dc40d64dd?pvs=4#2bb03321b6694bf8b747df643644a071