Create useGenericStore
MonashNovaRover/nova pull request #23
Opened 2024-09-29 10:29 UTC by FelicityMatt

## Description

Created useGenericStore to replace useLocalStorage. Basically a common and easy way to create redux stores which can then be easily used in a `[value, setValue]` way.

See [the doc I wrote](https://github.com/MonashNovaRover/nova/blob/7b64798df4f45cf712c7a5799134ce9a8a56debf/src/ros/nova-gui/docs/generic_store.md) for more detail.

fixes: #9 and helps #5 

Used `currentSite` as a way to test, will implement the SiteSelectWidget changes in a future PR.

## Changelogs

- create `createGenericStore`
- create `useGenericStore`
- when adding a new store default is to persist and tab sync -> the store must be manually blacklisted from both services if this functionality is not desired.

## Screenshots

[Screencast from 2024-09-30 09-12-49.webm](https://github.com/user-attachments/assets/593edc30-20c2-4cec-a502-0dfa14cbf6d9)

## Steps to Test

run the gui and check out the site selector and bottom counters. They both use `useGenericStore` and should persist and tab sync.

## Memes
![useGenericStore](https://github.com/user-attachments/assets/bd1d21f6-efff-461b-b83f-af64cb9d62bb)

2024-09-29 10:31 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/bifrost/bifrostStores.ts
> +export const bifrostStores = [
Since I wanted to make it as easy as possible to onboard new stores this had to be created to blacklist all of the bifrost stores, the other option is to white list stores, which would greatly reduce the list, but would be an extra on boarding step for generic stores, so lmk what would be preferred.

2024-09-29 10:33 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/views/test/TestStateView/SiteSelectWidget.tsx
> +const SiteSelectWidget: React.FC<SiteSelectWidgetProps> = (
Will move to this version of SiteSelectWidget in another pr, currently just a POC, not finalised yet

2024-10-02 09:56 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/RootReducer.ts
> +  currentSiteType: createGenericStore("currentSiteType", SpaceResourceSiteType.WATER),
not relevant to this PR but would we prefer site and site type to be two separate stores or combine them to be a single store with a struct? A single store seems cleaner and keeps the data together, but does involve a little more code for accessing and updating the values on the implementation side.

2024-10-03 07:54 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/RootReducer.ts
> +  currentSiteType: createGenericStore("currentSiteType", SpaceResourceSiteType.WATER),
Current site type is just some extra metadata the NIR Probe associates with each site. Probably best not to make this super tightly coupled with the site selector itself, so we can keep it generic

2024-10-09 09:33 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/hooks/useLocalStorage.ts
Im going to cry

2024-10-09 09:36 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/actions/useGenericStore.ts
> + * See the generic_store.md in the docs folder for more information
could this be a link to the doc? Fine if not tho

2024-10-09 10:37 UTC, BaileyChessum requested changes
Some minor performance considerations to look into for the validation checks on the hook, and a developer experience thing with automatically blacklisting bifrost stores/actions

2024-10-09 10:37 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/actions/useGenericStore.ts
> +  })
This is a lot of logic for a useSelector, which could impact performance. Could this logic be placed anywhere else, with less calls, that would still achieve the same logic?

2024-10-09 10:37 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/store/bifrost/bifrostStores.ts
> +  "baseLocationStore",
Could we automatically generate this from the RootReducer?

2024-10-13 01:50 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/bifrost/bifrostStores.ts
> +  "baseLocationStore",
I don't think we can since Root reducer is one big reducer and each field in it is a function so we can't check attributes.

2024-10-18 12:36 UTC, BaileyChessum requested changes
I really like this! I can't wait to start using this in GUI code. 

However, I have one minor gripe about the way you've written the `getReducers` function, which is a bit of a code smell. I think they way you use getReducers is weird. Why did you change `rootReducer` to be something different? Why not just make `getReducers` take the object as an input? Why does `getReducers` import the thing that generates the root reducer directly, rather than take it as an argument?

You should maybe think about getting in the habit of architecting your code for reusability, even if you aren't currently planning to reuse it. It simply encourages better and more maintainable designs. 

Think about your code as if you were making a library. Functions like `getReducers` should be independent on client code (i.e. the code specific to make our website). You should think about your code as if it is library code, that our client code consumes. It should be independent of logic specific to our website. 

Message me or arrange a time to call if you aren't sure exactly what I mean by this (particularly client code), and we can discuss it further.

Sorry if my comments seem pedantic, I am holding this to a slightly higher standard than normal, since this is effectively building the framework that our client code depends on. Client code can be sloppy, but I feel we should get the foundation right.

2024-10-18 12:36 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/store/rootReducerFilters.ts
> +export const getReducers = () => {
Should root reducer be generated from the given store object once, or should we regenerate every time we want to use it? 

I feel like you should keep `rootReducer` with its original type definition, and just define it as `rootReducer = getReducers(theThingYouCurrentlyNamedRootReducer)`

```ts
// TODO: Give this a better, cooler name
const thingThatGeneratesTheRootReducer = {
  // ...
};

export const rootReducer = getReducers(thingThatGeneratesTheRootReducer);
```

2024-10-18 12:36 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/store/configureRootStore.ts
> +    reducer: persistReducer(persistConfig, getReducers()),
see comment on function definition -- i think this line of code shouldn't have changed

2024-10-18 12:36 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/store/rootReducerFilters.ts
> +  const reducers = Object.keys(rootReducer).reduce((acc, val) => {
also, you should make the input to this function be a parameter, rather than referencing the thing you are currently calling `rootReducer` directly (it is no longer the rootReducer, but the thing that gets converted into the root reducer, and I don't think you should call it `rootReducer`)

Your code shouldn't be so dependent on our consuming code, it means it is super coupled to this one application, and can't be used anywhere else. Keep your code generic, reusable, and self-contained.

2024-10-18 12:36 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/RootReducer.ts
> +export const rootReducer = {
This shouldn't be called the `rootReducer`, as it is no longer the root reducer. It's the input that is used to generate the root reducer.

Instead, I think you should make the `rootReducer` the original type

```ts
// TODO: Give this a better, cooler name
const thingThatGeneratesTheRootReducer = {
  // Bifrost Stores
  bifrostStatus: BifrostStatusStore(),
  
  // ...
};

export const rootReducer = getReducers(thingThatGeneratesTheRootReducer);
```

2024-10-18 12:44 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/redux/store/bifrost/bifrostStores.ts
> +export const bifrostStores = [
this has been replaced by the new system for generating the `rootReducer`, right?

2024-10-18 21:05 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/rootReducerFilters.ts
> +export const getReducers = () => {
mm ok, i will fix this up, the only reason i left it as is was because i wanted to leave rootReducer unchanged so as the not confuse people who are familiar with the current setup

2024-10-19 03:40 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/bifrost/bifrostStores.ts
> +export const bifrostStores = [
yep this file does not exist anymore

2024-10-19 03:41 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/actions/useGenericStore.ts
> + * See the generic_store.md in the docs folder for more information
I wasn't able to link it to the file within the editor but have included a link to the doc in the master branch (which doesn't exist right now but will)

2024-10-19 03:42 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/actions/useGenericStore.ts
> +  })
moved to a useMemo which only runs on first render or when the storeName changes

2024-10-19 03:42 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/bifrost/bifrostStores.ts
> +  "baseLocationStore",
done

2024-10-19 03:42 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/rootReducerFilters.ts
> +export const getReducers = () => {
renamed to reduxStores

2024-10-19 03:43 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/rootReducerFilters.ts
> +  const reducers = Object.keys(rootReducer).reduce((acc, val) => {
done, did the same with useGenericStore and the filter functions

2024-10-19 03:43 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/RootReducer.ts
> +export const rootReducer = {
renamed to reduxStores and exported rootReducer at the bottom of the file

2024-10-19 04:08 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/redux/store/configureRootStore.ts
> +    reducer: persistReducer(persistConfig, getReducers()),
changed back

2024-10-20 03:27 UTC, BaileyChessum requested changes

2024-10-20 03:27 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/hooks/useLocalStorage.ts
> + *
Mark this with jsdoc @deprecated: https://jsdoc.app/tags-deprecated

2024-10-20 11:38 UTC, BaileyChessum approved these changes
LGTM

2024-10-20 11:39 UTC, merged