Fix competition view button
MonashNovaRover/nova pull request #80
Opened 2024-10-05 06:31 UTC by FelicityMatt

## Description

The top right competition view button now reflects the current page you are on.

fixes: #4 

## Changelogs

- button content dynamically changes with the view.

## Screenshots
![image](https://github.com/user-attachments/assets/1347117a-9aa9-47dd-8e5c-041d9bde002d)

## Steps to Test

- change views!

## Memes

![image](https://github.com/user-attachments/assets/af2707fa-1997-46bb-b3a8-bb6cfbc3b787)

2024-10-09 08:51 UTC, BaileyChessum commented
![image](https://github.com/user-attachments/assets/51bed8d4-8437-458d-918a-c75414725629)

2024-10-14 06:53 UTC, BaileyChessum requested changes

2024-10-14 06:53 UTC, BaileyChessum commented on src/ros/nova-gui/nova-gui/src/components/TopBar/TopBar.tsx
> +                  {prettyViewNames.has(viewName) ? prettyViewNames.get(viewName) : "General"}
Should the fallback name indicate that there is an error of some kind? Should it be "unknown" or something similar? 

Could get confusing unless the side navigation also shows general views when the view name is unknown.

2024-10-14 07:14 UTC, FelicityMatt commented on src/ros/nova-gui/nova-gui/src/components/TopBar/TopBar.tsx
> +                  {prettyViewNames.has(viewName) ? prettyViewNames.get(viewName) : "General"}
changed to ???

2024-10-17 04:32 UTC, BaileyChessum approved these changes
LGTM

2024-10-17 04:44 UTC, merged